version: '3.8'

services:
  # Remix アプリケーション
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=your-session-secret-here
      - OURA_CLIENT_ID=${OURA_CLIENT_ID}
      - OURA_CLIENT_SECRET=${OURA_CLIENT_SECRET}
      - OURA_REDIRECT_URI=http://localhost:3000/auth/callback
      - API_URL=http://api:8787
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - api
      - db
    command: npm run dev

  # Hono API (Cloudflare Workers風)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://oura:oura123@db:5432/oura_quest
      - JWT_SECRET=your-jwt-secret-here
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  # PostgreSQL (D1の代替)
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oura_quest
      - POSTGRES_USER=oura
      - POSTGRES_PASSWORD=oura123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # pgAdmin (データベース管理UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  postgres_data: