name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Debug - List files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in root:"
        ls -la
        echo "Package.json content:"
        cat package.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test -- run
    
    - name: Generate coverage report
      run: npm run test:coverage
      continue-on-error: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}